export const images = [
  {
    id: 1,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq1.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq2.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq3.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq4.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq5.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq6.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq7.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq8.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq9.png",
      "https://ukkibackend.soof.uz/media/photo/yaproq/yaproq10.png",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 2,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp1.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp2.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp3.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp4.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp5.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp6.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp7.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp8.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp9.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp10.png",
      "https://ukkibackend.soof.uz/media/photo/shtamp/shtamp11.png",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 3,
    mainImage: "https://ukkibackend.soof.uz/media/photo/sovun/sovun-asosiy.png",
    images: [],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 4,
    mainImage: "https://ukkibackend.soof.uz/media/photo/hosil/hosil-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil1.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil2.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil3.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil4.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil5.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil6.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil7.png",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil8.png",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil9.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil10.jpg",
      "https://ukkibackend.soof.uz/media/photo/hosil/hosil11.png",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 5,
    mainImage: "https://ukkibackend.soof.uz/media/photo/olma/olma-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/olma/olma1.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma2.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma3.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma4.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma5.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma6.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma7.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma8.png",
      "https://ukkibackend.soof.uz/media/photo/olma/olma9.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma10.jpg",
      "https://ukkibackend.soof.uz/media/photo/olma/olma11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 6,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/ad4ca49b-fb57-4199-939a-13aaffe2ad60.png",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt2.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt3.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt4.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt5.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt6.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt7.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt8.png",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt9.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt10.jpg",
      "https://ukkibackend.soof.uz/media/photo/daraxt/daraxt11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 7,
    mainImage: "https://ukkibackend.soof.uz/media/photo/qor/qor-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/qor/qor1.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor2.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor3.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor4.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor5.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor6.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor7.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor8.png",
      "https://ukkibackend.soof.uz/media/photo/qor/qor9.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor10.jpg",
      "https://ukkibackend.soof.uz/media/photo/qor/qor11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 8,
    mainImage: "https://ukkibackend.soof.uz/media/photo/archa/archa-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/archa/archa1.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa2.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa3.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa4.png",
      "https://ukkibackend.soof.uz/media/photo/archa/archa5.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa6.png",
      "https://ukkibackend.soof.uz/media/photo/archa/archa7.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa8.png",
      "https://ukkibackend.soof.uz/media/photo/archa/archa9.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa10.jpg",
      "https://ukkibackend.soof.uz/media/photo/archa/archa11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 9,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon1.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon2.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon3.png",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon4.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon5.png",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon6.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon7.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon8.png",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon9.png",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon10.jpg",
      "https://ukkibackend.soof.uz/media/photo/guldon/guldon11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 10,
    mainImage: "https://ukkibackend.soof.uz/media/photo/quyon/quyon-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon1.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon2.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon3.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon4.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon5.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon6.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon7.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon8.png",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon9.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon10.jpg",
      "https://ukkibackend.soof.uz/media/photo/quyon/quyon11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 11,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin1.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin2.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin3.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin4.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin5.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin6.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin7.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin8.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin9.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin10.jpg",
      "https://ukkibackend.soof.uz/media/photo/nastarin/nastarin11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 12,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak1.png",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak2.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak3.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak4.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak5.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak6.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak7.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak8.png",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak9.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak10.jpg",
      "https://ukkibackend.soof.uz/media/photo/kapalak/kapalak11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 13,
    mainImage: "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm-asosiy.jpg",
    images: [
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm1.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm2.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm3.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm4.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm5.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm6.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm7.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm8.png",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm9.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm10.jpg",
      "https://ukkibackend.soof.uz/media/photo/mmqaymoq/mm11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 14,
    mainImage:
      "https://ukkibackend.soof.uz/media/photo/kp/kp-asosiy.png",
    images: [
      "https://ukkibackend.soof.uz/media/photo/kp/kp1.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp2.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp3.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp4.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp5.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp6.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp7.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp8.png",
      "https://ukkibackend.soof.uz/media/photo/kp/kp9.png",
      "https://ukkibackend.soof.uz/media/photo/kp/kp10.jpg",
      "https://ukkibackend.soof.uz/media/photo/kp/kp11.jpg",
    ],
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
];
